[package]
name = "stack_pivot_poc"
version = "0.1.0"
authors = ["Michael Zandi <mzandi@blackberry.com>"]
license = "GPL-2.0 OR BSD-3-Clause"

[dependencies]
libbpf-rs = "0.14.0"
ctrlc = "3.1"

[build-dependencies]
libbpf-cargo = "0.9.3"
