/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package test.kotlin.coroutines

import kotlinx.coroutines.*

class App {
    val greeting: String
        get() {
            return "Standard Hello World!"
        }
}

fun main() = runBlocking {
    println(App().greeting)

    launch {
        delay(1000)
        println("example world")
    }
    println("example hello")
}
